### ISSUE TITLE
Clear the terminal after each roll

### ISSUE THREAD

**Issue by arpitnigam45** [acmpesuecc/snake-and-ladder-python#4]
After the dice gets rolled clear the terminal such that the initial grid gets cleared to make the new grid look better.

**Comment by Toshani** [comment]
Hi, I would like to try to work on this issue, please assign this to me.

**Comment by arpitnigam45** [comment]
Assigned

**Comment by arpitnigam45** [comment]
please come up with a solution that works for all operating system

**Comment by Toshani** [comment]
Sure, will try my best
